/* Main.c file generated by New Project wizard
 *
 * Created:   周四 1月 2 2020
 * Processor: 8086
 * Compiler:  Digital Mars C
 *
 * Before starting simulation set Internal Memory Size 
 * in the 8086 model properties to 0x10000
 */

#define BASE8255 8000H		//设定值

#define PA BASE8255+00H*2	//PA口
#define PB BASE8255+01H*2	//PB口
#define PC BASE8255+02H*2	//PC口
#define COM8255 BASE8255+03H*2	//工作方式
#define TIMEPORT 0F0C0H		//8253写控制字端口
#define TIME0 0F000H 		//8253 0号计数器

char xiangxu[8]={02H,06H,04H,0CH,08H,09H,01H,03H};

void outp(unsigned int addr, char data) {
   __asm {
      mov dx, addr //将addr移入dx
      mov al, data
      out dx, al //将al的值写入dx
   }
}

// Read a byte from the specified I/O port
char inp(unsigned int addr) {
   char result;

   __asm {
      mov dx, addr
      in al, dx
      mov result, al
   }

   return result;
}

void delay(int n)
{
   for(int i=0;i<n;i++)
   {
   }
}

//用于旋转的函数
//正向旋转的函数
void clockWise(int n)
{
   for(int i=0;i<8;i++)
   {
      outp(PB,xiangxu[i]);
      delay(n);
   }
}

//逆向旋转函数
void antiClockWise(int n)
{
   for(int i=7;i>=0;i--)
   {
      outp(PB,xiangxu[i]);
      delay(n);
   }
}

//用这个函数读取PA4的状态，确定计时是否结束
int  timeFinished()
{
   char tmp=inp(PA);
   if((tmp&0b00010000)==0b00010000)//PA4为1，则计时结束
      return 1;
   return 0;
}

//设置8253 0的时间值，以秒为单位
void setTime0(int n)
{
   outp(TIMEPORT,0b00010001);
   outp(TIME0,n);
   //outp(TIME0,0b00000000);
}

//首洗涤的旋转
void washFun(int washLevel,int time)
{
   //需要正转反转结合
   if(washLevel==1)
   {
      //for(int i=0;i<7;i++)
      setTime0(time);
      while(!timeFinished())
      {
	 for(int j=0;j<2;j++)
	    clockWise(1000);
	 delay(1000);
	 for(int j=0;j<2;j++)
	    antiClockWise(1000);
	 delay(1000);
      }
   }
   else if(washLevel==2)
   {
      //for(int i=0;i<5;i++)
      setTime0(time);
      while(!timeFinished())
      {
	 for(int j=0;j<2;j++)
	    clockWise(7000);
	 delay(7000);
	 for(int j=0;j<2;j++)
	    antiClockWise(7000);
	 delay(7000);
      }
   }
   else if(washLevel==3)
   {
      //for(int i=0;i<3;i++)
      setTime0(time);
      while(!timeFinished())
      {
	 for(int j=0;j<2;j++)
	    clockWise(20000);
	 delay(20000);
	 for(int j=0;j<2;j++)
	    antiClockWise(20000);
	 delay(20000);
      }
   }
}

//脱水用的函数，朝着一个方向快速转动即可
void dryOut(int time)
{
   setTime0(time);
   while(!timeFinished())
   for(int i=0;i<8;i++)
   {
      outp(PB,xiangxu[i]);
      delay(1500);
   }	
}

void main(void)
{



   //程序一直运行
   while(1)
   {
      char tmp,judge;
      int i=0;
      //设置工作方式：1 00 1 0 0 0 0（特征位=1，A组0方式=00，PA输入=1，PC上半没用到=0，B组0方式=0，PB输出=0，PC下半没用到=0）
      outp(COM8255,090H);//090H = 1001 0000
      //读PA口
      while(1)
      {
	 tmp=inp(PA);
	 //if(tmp&0b11100000==0b11100000)
	 if((tmp&0b00000011)==0b00000011)
	 {
	    //读取PA口，如果前三个都是一代表还没有按下一个键
	 }
	 else
	    break;
      }
      //judge用于判断工作状态，末两位10为洗涤，01为脱水
      judge=(tmp&0b00000011);
      
      int washLevel=1; //档位
      //根据输入确定挡位
      //if((tmp|0b01111111)==0b01111111)
      if((tmp&0b10000000)==0b00000000) //PA7为0
      {
	 washLevel=1;
      }
      //else if((tmp|0b10111111)==0b10111111)
      else if((tmp&0b01000000)==0b00000000) //PA6为0
      {
	 washLevel=2;
      }
      else if((tmp&0b00100000)==0b00000000) //PA5为0
      {
	 washLevel=3;
      }
      
      //确定时间
      int time=0;
      if((tmp&0b00001000)==0b00000000) //PA3为0
      {
	 time=8;
      }
      else if((tmp&0b00000100)==0b00000000) //PA2为0
      {
	 time=4;
      }
      
      int n=2;
      while (1){
	 n--;
	 if(n==0) break;
	 if(judge==0b00000010)
	 {  //洗涤
	    //设置洗涤状态灯亮
	    outp(PC,0b01000000);//PC6为1，洗涤灯亮
	    washFun(washLevel,time);
	    outp(PC,0b10000000);//PC7为1，脱水灯亮
	    dryOut(4);
	    outp(PC,0b00000000);//灯全灭
	 }
	 else if(judge==0b0000001)
	 {  //脱水
	    outp(PC,0b10000000);//PC7为1，脱水灯亮
	    dryOut(time);
	    outp(PC,0b00000000);//灯全灭
	 }
	 delay(1000);
      }
      outp(PC,0b00100000);//PC5为1
      delay(10000);
      outp(PC,0b00000000);//灯全灭
   }
}