/* Main.c file generated by New Project wizard
 *
 * Created:   周二 三月 15 2016
 * Processor: USB8086
 * Compiler:  Digital Mars C
 * StudentID: XXXXXXXXXX
 * Name:      XXXXXXXXXX
 *
 */

#define IN245    0D000H
#define OUT373   8000H

// Write a byte to the specified I/O port
void outp(unsigned int addr, char data) {
  __asm {
    mov dx, addr
    mov al, data
    out dx, al
  }
}

// Read a byte from the specified I/O port
char inp(unsigned int addr) {
  char result;
  
  __asm {
    mov dx, addr
    in al, dx
    mov result, al
  }
  
  return result;
}
 
char tmp;

/*
 * NOTE: Before starting simulation set Internal Memory Size
 * in the 8086 model properties to 0x10000
 */
void main(void) {
  while (1) {
    // Write your code here
    ;  
  }
}